### PR TITLE
Fix save feature

### LINKED ISSUE #967: Lines and polygons are not saved anymore in Mymaps.
Introduced by #956

### PR DESCRIPTION
**Pull request by rmichaelis**
fixes #967

### CODE REVIEW

**Comment by petzlux** [comment]
@rmichaelis you need to rebase changes after merge from other branches.

File: geoportailv3/static/js/draw/drawdirective.js [hunk 1]
```diff
@@ -440,6 +440,7 @@ app.DrawController.prototype.onDrawEnd_ = function(event) {
   this.selectedFeatures_.clear();
   this.selectedFeatures_.push(feature);
   this.featurePopup_.show(feature);
+  this.drawnFeatures_.saveFeature(feature);
```
Comment (petzlux) [inline geoportailv3/static/js/draw/drawdirective.js]: @rmichaelis Point, Label and Circle are saved twice to the MyMap .
