### PR TITLE
Set the base url only once

### LINKED ISSUE #1496: initUrls may be called several times
When several maps are added in a page the `initUrls` function may be called several times which results in wrong urls.

### PR DESCRIPTION
**Pull request by pgiraud**
Fixes #1496.
@tonio please review.

### CODE REVIEW

File: jsapi/src/main.js [hunk 1]
```diff
@@ -43,9 +43,25 @@ lux.searchUrl = 'fulltextsearch?';
 lux.baseUrl = null;
 
 /**
- * @param {string} url Base url to services
+ * @param {string|null} url Base url to services
```
Comment (tonio) [inline jsapi/src/main.js]: missing `@export` ?

Comment (pgiraud) [inline jsapi/src/main.js]: Good catch.
