### PR TITLE
Fix localStorage/permalink bug

### LINKED ISSUE #372: localstorage
the seems to be a problem with the localstorage:

http://devv3rm.geoportail.lu/?version=3&zoom=12&X=674880&Y=6390772
If you reopen the page without url params:
http://devv3rm.geoportail.lu/?version=3&zoom=8&X=16676259&Y=623889

I think that it does not use the version=3 parameter and then applies the coordinate system switch to the coordinates that are already in webmercator or something like that

### PR DESCRIPTION
**Pull request by elemoine**
Fix a bug where the map directive converts x, y and zoom from version 2 to version 3 when the values are read from the local storage. There should be no conversion when the values are read from the local storage. The conversions occur only when reading from the location URL, when there's no version parameter or when the version parameter is set to 2.

Depends on https://github.com/camptocamp/ngeo/pull/203.

Fixes #372.

### CODE REVIEW

**Comment by elemoine** [comment]
https://github.com/camptocamp/ngeo/pull/203 is now merged.

**Comment by elemoine** [comment]
Travis build now passes. Please review.

File: geoportailv3/static/js/statemanagerservice.js [hunk 1]
```diff
@@ -21,28 +21,59 @@ goog.require('ngeo.Location');
...
 
   /**
-   * @type {ngeo.Location}
+   * @type {Object.<string ,string>}
    * @private
    */
-  this.ngeoLocation_ = ngeoLocation;
-
-  var version = ngeoLocation.getParam('version');
+  this.states_ = {};
```
Comment (pgiraud) [inline geoportailv3/static/js/statemanagerservice.js]: I would name it `initialState_`.

**Comment by pgiraud** [comment]
As we just discussed, please use singular for state.
{{{
updateStates(states) -> updateState(object)
getInitialState(key) -> getInitialValue(key)
}}}

**Comment by elemoine** [comment]
Patch updated as discussed.

**Comment by elemoine** [comment]
Thanks for the review @pgiraud. Merging.

File: geoportailv3/static/js/map/mapdirective.js [hunk 2]
```diff
@@ -81,7 +81,7 @@ app.MapController = function(appStateManager, ngeoDebounce) {
   view.setCenter(viewCenter);
   view.setZoom(viewZoom);
 
-  app.MapController.updateParams_(appStateManager, view);
+  app.MapController.updateStates_(appStateManager, view);
```
Comment (pgiraud) [inline geoportailv3/static/js/map/mapdirective.js]: Let's be consistent and use `updateState_` here. Sorry I'm picky.

Comment (elemoine) [inline geoportailv3/static/js/map/mapdirective.js]: You're not picky at all. It's an oversight. Fixing now…
