### PR TITLE
Fix - Choose Map when no Map is owned by User

### LINKED ISSUE #919: Open a map when no map has been created yet
If the user never created any mymaps map and clicks on the "Open a map" button, nothing happens. The modal window doesn't show up.

Expected: the window should be open telling that there are no map available.

### PR DESCRIPTION
**Pull request by petzlux**
fix #919

### CODE REVIEW

File: geoportailv3/static/js/mymaps/mymapsdirective.js [hunk 1]
```diff
@@ -450,6 +450,10 @@ app.MymapsDirectiveController.prototype.openChooseMapModal = function() {
       } else if (!goog.array.isEmpty(mymaps)) {
         this.choosing = true;
         this.maps = mymaps;
+      } else if (goog.array.isEmpty(mymaps)) {
```
Comment (pgiraud) [inline geoportailv3/static/js/mymaps/mymapsdirective.js]: Is there an other case you are thinking of?
If not, I would use `else` with no condition.

**Comment by petzlux** [comment]
Code review complete will merge once travis is happy
